global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fraud-monitoring'
    static_configs:
      - targets: ['monitoring:9090']
    metrics_path: /metrics

  - job_name: 'predict-service'
    static_configs:
      - targets: ['predict-service:8000']
    metrics_path: /metrics
